export const Pagination = {
  prevPage: "prev",
  nextPage: "next",
  goto: "goto",
  page: "",
  sizeUnit: " / page",
};

export const DateTime = {
  hour: "Hour",
  minute: "Minute",
  second: "Second",
  now: "Now",
  today: "Today",
  thisMonth: "This Month",
  thisYear: "This Year",
  Su: "Su",
  Mo: "Mo",
  Tu: "Tu",
  We: "We",
  Th: "Th",
  Fr: "Fr",
  Sa: "Sa",
  Jan: "Jan",
  Feb: "Feb",
  Mar: "Mar",
  Apr: "Apr",
  May: "May",
  Jun: "Jun",
  Jul: "Jul",
  Aug: "Aug",
  Sep: "Sep",
  Oct: "Oct",
  Nov: "Nov",
  Dec: "Dec",
};
